disallow run-phase to be run directly - must be run via a phaseX symlink

diff --git a/src/scripts/run-phase b/src/scripts/run-phase
--- a/src/scripts/run-phase
+++ b/src/scripts/run-phase
@@ -2,7 +2,16 @@
 
 NODE="node -max-old-space-size=8192"
 
-PHASE=`basename "$0"`
+SYMLINK_NAME=`basename "$0"`
+SELF_NAME=`basename $(readlink -f $0)`
+
+if [ "$SYMLINK_NAME" = "$SELF_NAME" ]
+then
+    echo "This script cannot be run directly. Use either phase0, phaseA, phaseB, or phaseC."
+    exit 1
+fi
+
+PHASE="$SYMLINK_NAME"
 PYRET_JARR="build/$PHASE/pyret.jarr"
 FILE=$1
 
